// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniTodo.Data;

#nullable disable

namespace MiniTodo.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230303183032_addSeed")]
    partial class addSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("MiniTodo.Models.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f5420b8-6a12-445f-b1c1-be8d281698ad"),
                            CreatedAt = new DateTime(2023, 3, 3, 15, 30, 32, 325, DateTimeKind.Local).AddTicks(6658),
                            IsCompleted = false,
                            Title = "Teste 1"
                        },
                        new
                        {
                            Id = new Guid("f785d98b-bfdd-4b30-93b1-e2d91add94f9"),
                            CreatedAt = new DateTime(2023, 3, 3, 15, 30, 32, 325, DateTimeKind.Local).AddTicks(6696),
                            IsCompleted = false,
                            Title = "Teste 2"
                        },
                        new
                        {
                            Id = new Guid("f1dcd9a2-6826-4247-95b9-2448dba1b551"),
                            CreatedAt = new DateTime(2023, 3, 3, 15, 30, 32, 325, DateTimeKind.Local).AddTicks(6697),
                            IsCompleted = false,
                            Title = "Teste 3"
                        },
                        new
                        {
                            Id = new Guid("1ea00fca-1594-4d10-a66d-07ee71934e2c"),
                            CreatedAt = new DateTime(2023, 3, 3, 15, 30, 32, 325, DateTimeKind.Local).AddTicks(6701),
                            IsCompleted = false,
                            Title = "Teste 4"
                        },
                        new
                        {
                            Id = new Guid("b3c5dfb8-c27c-415e-be31-57c66cb0f65a"),
                            CreatedAt = new DateTime(2023, 3, 3, 15, 30, 32, 325, DateTimeKind.Local).AddTicks(6703),
                            IsCompleted = false,
                            Title = "Teste 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
